---
# tasks file for ruby
#- name: Pull Key from gpg Server
#  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

- name: Install Curl, Ruby _ Sudo Style
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  become: yes
  with_items:
    - curl
    - ruby

- name: Install Ruby  when Amazon Linux
  shell: amazon-linux-extras install ruby2.4 -y 
  when: ansible_distribution == "Amazon"
  become: yes

- name: Install Ruby-Railties when Debian Linux
  action: >
    {{ ansible_pkg_mgr }} name=ruby-railties state=present update_cache=yes
  when: ansible_os_family == "Debian" 
  become: yes

- name: curl rvm
  shell: curl -sSL https://get.rvm.io | bash 

- name: Source rvm script & rvm install ruby
  shell: source {{ ansible_env.HOME }}/.rvm/scripts/rvm  && rvm install ruby
  args:
    executable: /bin/bash

- name: Install Ruby Bundler Gem when DEBIAN
  register: gem
  when: ansible_os_family == "Debian"
  shell: source {{ ansible_env.HOME }}/.rvm/scripts/rvm  && gem install bundler
  become: true
  args:
    executable: /bin/bash
- debug: var=gem.stdout_lines

- name: Install Ruby Bundler Gem when REDHAT
  register: gem
  when: ansible_os_family == "RedHat"
  shell: source {{ ansible_env.HOME }}/.rvm/scripts/rvm  && gem install bundler >> background 2>&1 &
  become: true
